### ISSUE TITLE
fix: signReleaseBundle

### ISSUE THREAD

**Issue by Fudal** [shorebirdtech/shorebird#1165]
**Description**

In my github workflow my action was failed with error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:signReleaseBundle'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.FinalizeBundleTask$BundleToolRunnable
   > java.lang.NullPointerException (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 11m 1s
Gradle task bundleRelease failed with exit code 1
 (693.0s)
Error: Process completed with exit code 70.
```

**Steps To Reproduce**

That is my job content:

```
name: Shorebird Patch

on:
  push:
    tags:
      - "v*shorebird"

jobs:
  patch:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: Setup Environment Variables
        run: ./.github/scripts/setup_env.sh

      - name: 🐦 Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: 🚀 Shorebird Android Patch
        run: shorebird patch android
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
```

**Expected Behavior**

Action is finish with success. Patch is deployed.

**Comment by eseidel** [comment]
I wonder if your CI is trying to sign the apk and failing to find the signing cert?  I'm confused why it's crashing in java (possibly the gradle binary itself?)

If you can reproduce the crash, it looks like pasing --stacktrace to gradle might help.

**Comment by SebastianEngel** [comment]
I just ran into the same problem when setting up the Shorebird patch workflow. I realized that since Shorebird is building another release artifact for the diff comparison it needs to sign the artifact. And for that it needs the signing information. In our case the signing information (e.g. `key.properties`) is not stored in the repository. Instead our release workflow creates the `key.properties` file and writes the values from Github Secrets into it. I copied the respective steps from our release workflow over to the patch workflow (before the Shorebird steps) and not it works.

@eseidel Might this hint be helpful for the [CI documentation](https://docs.shorebird.dev/ci/github)?

**Comment by bryanoltman** [comment]
@SebastianEngel Thanks for this! I'm looking at making a doc update now. To make sure I'm understanding correctly, you're suggesting a "make sure you `key.properties` is in place before running `shorebird patch` or `shorebird release`" callout?

**Comment by SebastianEngel** [comment]
@bryanoltman Yes, I think it would additionally help to point out that `shorebird patch` includes building and signing a release. Therefore, similar as for `shorebird release`, all signing information is required to be in place.
