### ISSUE TITLE
fix: can't run shorebird on Mac Intel

### ISSUE THREAD

**Issue by jonathan-sahar** [shorebirdtech/shorebird#1263]
When I to install shorebird and run shorebird command line i got this line: 

Shorebird Engine • revision 5a1c263ce5313c8f5e93a11dd2a3af0e19d90262
'sysctl -n hw.optional.arm64' returned unexpected output: ''.

I try reinstall and the issue still the same

**Comment by bryanoltman** [comment]
Which command did you run?

**Comment by jonathan-sahar** [comment]
after install i run shorebird.

**Comment by bryanoltman** [comment]
What command though? Are you just typing `shorebird` in your terminal? I just verified that I was able to release, patch, and preview an iOS app with shorebird on an x86 Mac, so I'm going to need more information to help.

**Comment by eseidel** [comment]
Related to https://github.com/shorebirdtech/shorebird/issues/939?

**Comment by eseidel** [comment]
I think it's an apple bug and a flutter bug (and we should probably find a way to help Flutter work around the apple bug):
https://github.com/flutter/flutter/issues/116408 is another report.

**Comment by eseidel** [comment]
FYI @christopherfujino, we've gotten a couple of reports of these where some machines sometimes return '' instead of 1 or 0.  I suspect the logic in update_dart_sdk (which you were the last person to touch 🙃 ) should be updated to either include '' to mean x86, or use `arch` or `uname`:
https://github.com/flutter/flutter/blob/master/bin/internal/update_dart_sdk.sh#L67
https://stackoverflow.com/questions/65259300/detect-apple-silicon-from-command-line

**Comment by eseidel** [comment]
Filed https://github.com/flutter/flutter/issues/134766

**Comment by jonathan-sahar** [comment]
> What command though? Are you just typing `shorebird` in your terminal? I just verified that I was able to release, patch, and preview an iOS app with shorebird on an x86 Mac, so I'm going to need more information to help.

any command i run it will run the Flutter update and then the error happend. shorebird login, shorebird ..etc..

**Comment by jonathan-sahar** [comment]
> Related to #939?

thanks. this help me solve the issue
