### ISSUE TITLE
The release artifact contains native changes, which cannot be applied with a patch

### ISSUE THREAD

**Issue by irfnyas** [shorebirdtech/shorebird#1286]
```
Run shorebird patch android
⠋ Fetching apps...
✓ Fetching apps (0.3s)
⠋ Building patch...
✓ Building patch (392.9s)
⠋ Detecting release version...
✓ Detected release version 2.2.0+1 (1.1s)
⠋ Fetching releases...
✓ Fetching releases (0.2s)
⠋ Fetching release artifacts...
✓ Fetching release artifacts (0.2s)
⠋ Fetching aab artifact...
✓ Fetching aab artifact (57ms)
⠋ Downloading release artifacts...
✓ Downloading release artifacts (1.1s)
⠋ Verifying patch can be applied to release...
✓ Verifying patch can be applied to release (1.6s)
[WARN] The release artifact contains native changes, which cannot be applied with a patch.
    Changed files:
        base/dex/classes.dex
Exiting.
Error: Process completed with exit code 70.
```

I don't have this warning when running the patch from local. What's the issue and how to fix it?

**Comment by eseidel** [comment]
We definitely could have a more informative message there.

classes.dex is the compiled Java/Kotlin code.  So typically that means either your changes include some java/kotlin changes or in some cases it could be you didn't change any java/kotlin but a dependency did (e.g. a flutter plugin) or even less common, sometimes there are gradle dependendencies/gradle plugins which modify the build every time it's made (e.g. to add a timestamp of when the build happened) which can cause this type of change to appear every time.

Depending on which of those cases you think you fall into, it could be safe to continue, it could not be.  Worst case your app will behave differently than you expect after patching, since it would only contain the Dart changes, and none of the Java/Kotlin changes.

**Comment by eseidel** [comment]
I think this bug could/should be resolved by us giving a longer explainer when this happens, or at least linking to docs which explain what happened.
