### ISSUE TITLE
fix:  No artifact found for architecture xcarchive in release 

### ISSUE THREAD

**Issue by Oladips** [shorebirdtech/shorebird#1321]
**Description**

I tried to make an ios patch to my app and I get this error message after building patch

**Screenshots**

<img width="564" alt="Screenshot 2023-09-25 at 14 09 45" src="https://github.com/shorebirdtech/shorebird/assets/45954324/fe53c2b0-2456-4f9a-a72d-afaf678d32c8">

**Comment by Oladips** [comment]
And I already have 9 patch updates on this app prior this

**Comment by eseidel** [comment]
Looks like fallout from your xcarchive changes @bryanoltman ?

**Comment by Oladips** [comment]
Xarchive changes in my current build??

**Comment by bryanoltman** [comment]
In a recent release of shorebird, we switched from using `.ipa` files as our release artifact to using `.xcarchive` files, because `.xcarchive` files are generated regardless of whether code signing happens as part of the build, whereas `.ipa` files are only generated after code signing. I think what is happening here is that you created the initial release was created with a version of shorebird that used `.ipa`s as the release artifact, and the current version of shorebird doesn't know how to patch that. You should be able to patch the release by using an older version of shorebird, which you can do by:

```bash
cd ~/.shorebird
git checkout v0.14.8
rm -rf ~/.shorebird/bin/cache
```

Let me know if that works!

**Comment by Oladips** [comment]
Yes it fixes it, Thanks.
I'll have to push a new release with the new version to start using xcarchive.

**Comment by jtmuller5** [comment]
I tried following these steps but the shorebird patch command fails with the following message:
```
✗ Fetching apps (0.1s)
Your version of shorebird is out of date.
```

Is there any way to force shorebird to skip the version check? I know I should just update but if I can push a patch sooner that would be awesome.

**Comment by eseidel** [comment]
> I tried following these steps but the shorebird patch command fails with the following message:
> 
> ```
> ✗ Fetching apps (0.1s)
> Your version of shorebird is out of date.
> ```
> 
> Is there any way to force shorebird to skip the version check? I know I should just update but if I can push a patch sooner that would be awesome.

I'm not sure if this is related to the earlier part of the issue or not.  You might want to file a new issue if it isn't so we don't forget your comments on a closed issue.

Regardless, I don't believe there is a way to skip the check.  Right now we have a tight coupling between our servers and the command line interface, so when we change our servers old versions of the CLI no longer work.

**Comment by jtmuller5** [comment]
Thanks for the quick reply! In that case I'll just move forward with the update.

**Comment by eseidel** [comment]
We're considering decoupling our CLI and server, but haven't yet.  For now any time we do a "Breaking change" (and bump the minor version) all CLIs must update.  Let us know if you have any trouble.  https://discord.gg/shorebird
