### ISSUE TITLE
feat: [Documentation] Decisions around when to use, when to enable/disable, how to communicate with stakeholders.

### ISSUE THREAD

**Issue by neiljaywarner** [shorebirdtech/shorebird#1333]
apologies if some of this was better for the discord server, but
1) Docs say quite reasonably that this is for critical features.  Can you give more opinion/info even pros/cons about both extremes on that?  
a) Why should it not be used for nearly every feature to avoid possible 1 week delays from stores? Is it just a matter of minor communication and infrastructure overhead?
b) on the other extreme, if someone is nervous and wants to "disable" shorebird except for super critical updates, could the engine be turned off / hidden behind split.io, launchdarly, firebase remote config or similar?  For example, if it was in remote config they could easily be in an audience behind a "use critical updates" toggle in settings that is either defaulted on or offf, giving the user more control while still using default simple behaviour for a shorebird code/setup perspective potentially

2) Any more information about how to communicate the "risks' of it if any. Perhaps the guarantee to not see your code and work towards on premise solution are sufficient or even all that is feasible, but just in case.

Fantastic work; i had a company that chose RN back in the day because of code push.

**Comment by eseidel** [comment]
> 1.a) Why should it not be used for nearly every feature to avoid possible 1 week delays from stores? Is it just a matter of minor communication and infrastructure overhead?

I think this is mostly a question of store policy.  Shorebird technology supports updating any amount of Dart code, but the agreement you sign with the various stores typically intend to restrict what sorts of features you're allowed to update with technologies like Shorebird:
https://docs.shorebird.dev/faq#does-shorebird-comply-with-play-store-guidelines

> 1. b) on the other extreme, if someone is nervous and wants to "disable" shorebird except for super critical updates, could the engine be turned off / hidden behind split.io, launchdarly, firebase remote config or similar? For example, if it was in remote config they could easily be in an audience behind a "use critical updates" toggle in settings that is either defaulted on or offf, giving the user more control while still using default simple behaviour for a shorebird code/setup perspective potentially

Shorebird is a replacement for the Flutter engine (it's a modified version of the Flutter engine) so the only way to turn it off/on is to recompile.  Of course you can recompile at any time using `flutter` instead of `shorebird` (`shorebird release` is designed to be a drop-in replacement for `flutter build`).

But Shorebird can only update app releases which were built with the Shorebird engine included.  This is because app releases aren't actually *pushed* to devices, so much as the devices (via the Shorebird engine) know how to *pull* the updates.

https://docs.shorebird.dev/uninstall discusses how to remove Shorebird should you wish to.

> 2 Any more information about how to communicate the "risks' of it if any. Perhaps the guarantee to not see your code and work towards on premise solution are sufficient or even all that is feasible, but just in case.

I'm not sure what risks you have in mind.  All things have some amount of risks.  I guess top of our list is always making sure that the Shorebird engine we provide you functions exactly as well as an unmodified Flutter engine does.  We obviously also worry about your privacy and security (and the privacy and security of your users) and work to ensure such is always maintained.  See shorebird.dev/privacy.

**Comment by eseidel** [comment]
I think these are mostly replied to in the faq's so I'm going to close this for now.  Thanks for the questions!
