### ISSUE TITLE
feat: Remove patch

### ISSUE THREAD

**Issue by the-best-is-best** [shorebirdtech/shorebird#1380]
**Description**

I uploaded a new patch, but it is by wrong and need to remove it to app work.

**Comment by albinpk** [comment]
> We have not yet added the ability to rollback patches. For now, the simplest thing is to simply push a new patch that reverts the changes you want to undo.

_:From docs_

**Comment by eseidel** [comment]
@albinpk is correct, there is currently no way to delete a patch from the console.  I would be relatively easy to add, we just hadn't had a request for such until now.  I'll add this to our queue, let us know if pushing a new patch was not a good enough work-around.

Currently as implemented, if we allowed you to delete a patch from the console, that would not change anything about devices who had already installed that patch, where as if you push a new patch that would install the new patch on all devices.

**Comment by martin-bertele** [comment]
+1

**Comment by eseidel** [comment]
I spoke with one customer and their desire was to have a "remove" button specifically to stop serving iOS patches due to current issue.  (There is a bug in Shorebird 0.20.0, 0.21.0 and 0.21.1 with Flutter 3.16.5 whereby sometimes iOS apps can crash after using `patch ios-alpha` : https://github.com/shorebirdtech/shorebird/issues/1623.)

**Comment by susantimilsina** [comment]
@eseidel I experienced crashes in the latest version as well. Initially, I doubted my step-by-step process, which is why I suggested creating a video featuring apps from both the Play Store and the App Store(If you remember i had left a comment on youtube channel). This was to verify if I was following the correct steps. However, considering the crashes reported by users, it seems the issue persists in the newer version too. I am using this versions.
Shorebird 0.23.0 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.16.7 • revision dea76906e4e34285a1910563efac89f4766cd649
Engine • revision d50060c4046447ce7edf24008d24b1be7fd953f0

**Comment by eseidel** [comment]
> @eseidel I experienced crashes in the latest version as well. Initially, I doubted my step-by-step process, which is why I suggested creating a video featuring apps from both the Play Store and the App Store(If you remember i had left a comment on youtube channel). This was to verify if I was following the correct steps. However, considering the crashes reported by users, it seems the issue persists in the newer version too. I am using this versions. Shorebird 0.23.0 • [git@github.com](mailto:git@github.com):shorebirdtech/shorebird.git Flutter 3.16.7 • revision dea76906e4e34285a1910563efac89f4766cd649 Engine • revision d50060c4046447ce7edf24008d24b1be7fd953f0

Thank you for the report!  We would love to help diagnose and fix the crashes.  Are you able to file an issue with a crash report?  We're also reachable on https://discord.gg/shorebird as well as contact@shorebird.dev if needed.  Thank you.

**Comment by bryanoltman** [comment]
We now support deleting patches from the console.

**Comment by SebastianEngel** [comment]
> We now support deleting patches from the console.

How is possible? For a live patch I see the "Roll Back" action and for a staged patch there is the "Activate" action. How can I delete the staged patch?

**Comment by bryanoltman** [comment]
I misspoke above. Patches cannot be deleted, but they can be deactivated or rolled back.
