### ISSUE TITLE
fix: Invalid `Podfile`

### ISSUE THREAD

**Issue by Fudal** [shorebirdtech/shorebird#1431]
**Description**

I can't build my iOS app version. I have error:

```
[!] Invalid `Podfile` file: cannot load such file -- /Users/mac1/.shorebird/bin/cache/flutter/ef4b661ddc0c71b738432ae59c6bc573e917854b/packages/flutter_tools/bin/podhelper.

 #  from /Users/mac1/Documents/app_name/ios/Podfile:26
 #  -------------------------------------------
 #  
 >  require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
 #  
 #  -------------------------------------------
```

**Steps To Reproduce**

1. `shorebird cache clean`
2. `cd ios`
3. `arch -x86_64 pod install --repo-update`

**Expected Behavior**

Repo update successful without error.

**Additional Context**

Before `shorebird cache clean` I had an error:
```
[!] An error occurred while processing the post-install hook of the Podfile.

/Users/mac1/.shorebird/bin/cache/flutter/ef4b661ddc0c71b738432ae59c6bc573e917854b/bin/cache/artifacts/engine/ios/Flutter.xcframework must exist. If you're running pod install manually, make sure "flutter precache --ios" is executed first
```

Of course `flutter precache --ios` didn't help.

**Comment by eseidel** [comment]
This looks like this:
https://docs.shorebird.dev/troubleshooting#i-installed-shorebird-and-now-i-cant-run-my-app-in-vs-code aka https://github.com/Dart-Code/Dart-Code/issues/4607.

I suspect you're in VSC.  VSC has some behavior where it reads the flutter path from .dart_tool/package_config.json.  In this case it's found Shorebird's vended Futter which is not a complete Flutter copy.

The fix is to remove .dart_tool/package_config.json from your flutter project and re-open the VSC terminal I believe.

**Comment by eseidel** [comment]
Please let us know if that does not resolve the issue.  We're also reachable on Discord every day: https://discord.gg/shorebird.

**Comment by eseidel** [comment]
You clarified over discord that this does not involve VSC, reopening.

**Comment by bryanoltman** [comment]
Ok, so the overall issue here seems to be that the Podfile generated by Flutter looks to `ios/Flutter/Generated.xcconfig` to determine where Flutter is, and I'm seeing `FLUTTER_ROOT` getting set to `/Users/bryanoltman/shorebirdtech/_shorebird/shorebird/bin/cache/flutter/012153de178d4a51cd6f9adc792ad63ae3cfb1b3` on a local project. Going to dig in to figure out why this is happening.

**Comment by bryanoltman** [comment]
@Fudal A quick fix would be to replace `FLUTTER_ROOT` with the path to your Flutter (the output of `which flutter` without the `bin/flutter` at the end)

**Comment by bryanoltman** [comment]
`flutter build ios` (and presumably `flutter build ipa`, which is the command shorebird uses) updates `ios/Flutter/Generated.xcconfig` to point to shorebird's version of flutter. We added a call to `flutter pub get` at the end of our build commands to fix a similar issue with `.dart_tool/package_config.json`, but that doesn't seem to work for Generated.xcconfig. Running `flutter clean` and then `flutter pub get` does fix this issue and is probably the solution.

That said, I'm struggling to get a new project into a state where this is happening. Digging more to make sure this is actually the issue.

**Comment by Fudal** [comment]
I confirm that changing the value for the `FLUTTER_ROOT` variable in the `Generated.xcconfig` file solves this problem.

**Comment by bryanoltman** [comment]
Great to hear! I've managed to reproduce locally.

Steps:

1. Create a new flutter project, init shorebird
2. Do an iOS release `shorebird release ios-alpha`
3. Note that `Generated.xcconfig` has a `FLUTTER_ROOT` value pointing to shorebird's version of Flutter
4. `cd ios` in my_new_project
5. Run `pod install`
6. Note that it works
7. `cd .. && shorebird cache clean`
8. `cd ios && pod install`
9. Note the failure.

So there are a couple things happening here:

1. `Generated.xcconfig` is pointed at a shorebird-vended flutter, causing cocoapods to use this Flutter instead of the system Flutter. This is wrong, but because shorebird doesn't make any changes to `podhelper`, this works.
2. `shorebird cache clean` deletes the shorebird-vended Flutter, which causes `pod install` to fail because it's trying to find `shorebird/bin/cache/flutter/[hash]/packages/flutter_tools/bin/podhelper`, which was just deleted.

A fix for this will ultimately involve pointing `Generated.xcconfig`'s `FLUTTER_ROOT` to point to non-shorebird flutter. There are a few possible ways to do this:

1. Run `flutter clean` as part of `shorebird cache clean`. This would probably be unexpected by our users, would not address the issue  that `Generated.xcconfig` is pointing to shorebird Flutter the rest of the time. 
2. Run `flutter clean` before `flutter pub get` on iOS builds. This would make our releases take longer and be more disruptive, but is probably the most correct option.
3. Manually edit `Generated.xcconfig` after iOS builds. This seems awful for a whole host of reasons.
4. Do nothing, tell users to run `flutter clean` if they encounter this issue.

**Comment by bryanoltman** [comment]
Also worth noting: `ios/Flutter/flutter_export_environment.sh` also contains `FLUTTER_ROOT`, and it also points to shorebird's flutter.

**Comment by bryanoltman** [comment]
Because this issue requires a very specific set of steps to reproduce, I've opened a PR to add a section to our troubleshooting docs to address it rather than attempting to fix this in code. We can revisit if the `Generated.xcconfig` `FLUTTER_ROOT` issue causes other problems down the road.
