### ISSUE TITLE
invalid active developer path 

### ISSUE THREAD

**Issue by OnClickListener2048** [shorebirdtech/shorebird#1436]
**Description**

I created a flutter application project and i shorebirt init i got this xcrun: error: invalid active developer path (/Applications/Xcode.app/Contents/Developer), missing xcrun at: /Applications/Xcode.app/Contents/Developer/usr/bin/xcrun
Updating Flutter...
xcrun: error: invalid active developer path (/Applications/Xcode.app/Contents/Developer), missing xcrun at: /Applications/Xcode.app/Contents/Developer/usr/bin/xcrun

I don't know what is going on

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**

**Additional Context**

**Comment by eseidel** [comment]
I've seen this before, it's a Mac XCode problem.  For me it was fixed by `sudo xcode-select --reset`, but it seems other have also fixed it with --install:
https://apple.stackexchange.com/questions/254380/why-am-i-getting-an-invalid-active-developer-path-when-attempting-to-use-git-a

Let us know if that doesn't resolve things!
