### ISSUE TITLE
Cannot create an ad-hoc iOS release

### ISSUE THREAD

**Issue by mickcurry** [shorebirdtech/shorebird#1441]
**Description**
release ad-hoc ipa failed

**Steps To Reproduce**
1. when I run this in terminal :
"shorebird release ios-alpha -- --export-method=ad-hoc"
to release a ad-hoc ipa
failed. 
2.here is the error message:
 Failed to build: "--export-options-plist" is not compatible with "--export-method". Either use "--export-options-plist" and a plist describing how the IPA should be exported by Xcode, or use "--export-method" to create a new plist.

**Expected Behavior**
1.  release  ad-hoc ipa successful
2.  by the way , we also need  to release enterprise ipa
<img width="556" alt="Screenshot 2023-10-31 at 17 26 51" src="https://github.com/shorebirdtech/shorebird/assets/139640478/765c498b-442c-45a3-9d30-d7294c1a6fec">

**Screenshots**
<img width="1622" alt="Screenshot 2023-10-31 at 17 21 32" src="https://github.com/shorebirdtech/shorebird/assets/139640478/3894808f-bbad-451e-842f-042c86e44167">

**Additional Context**
we will buy your service if all these issues fixed. we really need the OTA ability of shorebird, thanks.

**Comment by bryanoltman** [comment]
This is happening because our tooling provides the `--export-options-plist` argument to `flutter build ipa` internally. We can introduce tooling to fix this, but a workaround that I believe should work is to create your own plist file with the contents:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-/
<plist version="1.0">
<dict>
  <key>method</key>
  <string>ad-hoc</string>
</dict>
</plist>
``` 

Let's call that `adhoc.plist`

Running `shorebird release ios-alpha -- --export-options-plist=adhoc.plist` should do what you want.
