### ISSUE TITLE
fix: `shorebird` sometimes uses the wrong app.dill file

### ISSUE THREAD

**Issue by alamsyahh15** [shorebirdtech/shorebird#1444]
**Description**

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**

**Additional Context**

I want to running patch using shorebird but there's have an error like this image :
<img width="785" alt="Screenshot 2023-11-02 at 14 07 15" src="https://github.com/shorebirdtech/shorebird/assets/55674991/ccca6d94-4561-4be4-9f77-4ae321e575d0">

**Comment by eseidel** [comment]
Wow, that's a very surprising error.  Thank you for letting us know.

**Comment by eseidel** [comment]
I think this is gen_snapshot crashing?  Note the "sim=yes" that suggests whatever it is it's running in our simulator mode.  However it's also running on macos (not a device) so nothing there should *need* to be in simulator mode.  Something has gone wrong (possibly in the way we're building our artifacts).

gen_snapshot also takes .dill files (not sure about "concatenated dill files" though).

I'm not sure from the output if this is a patch command or release command.  My guess is it's a patch command since that's going to run gen_snapshot:
https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/commands/patch/patch_ios_command.dart#L302

I wonder if the gen_snapshot we're using is from the simulator side of our build by accident?

Oh, nevermind, it looks like we don't build gen_snapshot separately. 🤣   So yes it is from teh simulator side:
https://github.com/shorebirdtech/build_engine/blob/main/build_engine/mac_build.sh#L70

That's just making gen_snapshot needlessly slow.  Notice how when doing development we do the gen_snapshot w/o the simulator:
https://github.com/shorebirdtech/ffi_test#building

That still doesn't explain this crash, but it might be contributing to it.

**Comment by eseidel** [comment]
Explanation of a concatenated dill file: https://github.com/dart-lang/sdk/commit/07b6ec3425443449c52793253bf74c6b1f06a474

**Comment by eseidel** [comment]
AH.  I bet what this is @bryanoltman is that our method for finding the right .dill to load is failing, so we're sending some other .dill to gen_snapshot and thus getting this error:
https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/shorebird_artifact_mixin.dart#L177
So that's the bug, just manifesting in this nutty way.

There is also a separate bug (which I'll file separately) about us not needing to use a sim build of gen_snapshot to build.

**Comment by eseidel** [comment]
Filed https://github.com/shorebirdtech/_shorebird/issues/1728 about gen_snapshot not needing to have the simulator on.

**Comment by eseidel** [comment]
In terms of working around this @alamsyahh15, I would expect you should just be able to `shorebird release` again and it will work.  If that doesn't work, try `shorebird clean` and then it should.  I believe the error is caused by us finding the wrong .dill file in the `.dart_tool` under your project directory, `shorebird clean` or `flutter clean` should delete that directory and it should find the correct dill file the next run.

**Comment by eseidel** [comment]
The "right" solution for this may be that we write a tiny C++ program in the Dart SDK which knows how to read the Dart Snapshot out of a Mach-O file and write it out into an Elf file.  Dart has all those pieces, we just need to string them together.

Another solution would be to modify the `flutter` tool to somehow communicate better what .dill path it was using.  Which maybe is easier?

**Comment by eseidel** [comment]
We actually even have the "dump the snapshot out of that mach-o file", but I think this is happening during `patch` when we rebuild the dart code a second time.  My guess (without fully paging this in) is that we have to some how get the correct app.dill path out of the `flutter` tool, possibly by parsing its logs or modifying it to save it to a known location?
