### ISSUE TITLE
Update "does shorebird work from my country" faq

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1506]
The point is to explain to customers how to teach reachability of shorebird's servers.

Maybe instead we should include this as part of `shorebird doctor`?

Confusion: https://discord.com/channels/1030243211995791380/1174569116875628574/1174571036059115520

**Comment by eseidel** [comment]
See also https://github.com/shorebirdtech/shorebird/issues/1505

**Comment by bryanoltman** [comment]
Reopening as it's possible for storeage.googleapis.com to be pingable but to have uploads blocked (by a firewall, for example). The correct fix will likely involve trying to upload a very small file as a test.

**Comment by bryanoltman** [comment]
For context, this issue originated from a user who was unable to upload artifacts to storage.googleapis.com. This ended up being caused by an antivirus installed on their machine. storage.googleapis.com was pingable, so we should 1) see whether both uploads and downloads are affected (vs only uploads) and 2) have doctor test downloads (if they're affected) or uploads (if downloads still work)
