### ISSUE TITLE
Android patches have an insane input lag

### ISSUE THREAD

**Issue by blk-raffy** [shorebirdtech/shorebird#1547]
**Description**

The release version works smoothly but when a patch is applied the app became insanely laggy. I've received so many messages from my customers that i decided to tested it. I've tried it on a Samsung S23 Ultra and a Nothing Phone 2 and it seems like there is a sort of input lag on the gestures like onTap, onDoubleTap, onSwipe and so on. In the release version it was all working fine.

**Steps To Reproduce**

1. Create a release
2. Install it from the Google Play Store
3. Apply a patch
4. Open the app and it starts to lag

**Expected Behavior**

Without input lag

**Screenshots**

**Additional Context**

I haven't received yet any issue from ios' users

**Comment by eseidel** [comment]
I would love to learn more.  Shorebird on Android should not be any slower in a patch vs. release.  Are you able to see the input lag with `shorebird preview`?  Do you see the input lag when running in just flutter (without shroebird)?

**Comment by blk-raffy** [comment]
The preview seems kinda fluid. My app is about 50MB, idk if this bundle size can affect the patch's performances. I'm about to release another version of the app because the map (mapbox), after 2 little patches (where both doesn't changed nothing in the map logic) gets up to 8 seconds to load the widget.
Buttons and Tiles have something like 800ms/1s of delay to execute onTap function and it's kinda annoying. 

Let me know if I can do something to try to fix

**Comment by felangel** [comment]
> The preview seems kinda fluid. My app is about 50MB, idk if this bundle size can affect the patch's performances. I'm about to release another version of the app because the map (mapbox), after 2 little patches (where both doesn't changed nothing in the map logic) gets up to 8 seconds to load the widget. Buttons and Tiles have something like 800ms/1s of delay to execute onTap function and it's kinda annoying.
> 
> Let me know if I can do something to try to fix

It would be great if you could provide a minimal reproduction sample for us to debug, thanks!

**Comment by blk-raffy** [comment]
I think it would take some times because the code is under an NDA. I will send you the code as soon as possible, thanks

**Comment by blk-raffy** [comment]
Ok i spoke to the cto and we cannot provide any code due to the NDA. Yesterday we've released another patch and all the users now have a black screen, the flutter activity doesn't boots up. 

Shorebird is a nice project, but I think it's not ready for production yet. Keep going and thanks for the support. Have a nice day

**Comment by eseidel** [comment]
To clarify:
- I agree with your CTO, we also can't view others code outside of an NDA.  The best solution is typically to reduce a bug to smaller amount of code which is safe to post publicly (then no one has to sign anything).
- We've not had anyone report of input lag related to Shorebird.  I don't see how Shorebird could cause input lag, but I'd love to learn more if you believe it related to Shorebird.
- Something like a black screen could be caused by making a patch which changes Dart code but depends on non-Dart code also changing.  Shorebird warns about this case in the tool, but it's also possible for users to override this warning.  I don't know if that's the case here, see: https://docs.shorebird.dev/troubleshooting#unexpected-native-changes
- I'm sad to hear that you've had difficulty with Shorebird.  We're happy to help you debug, but we don't have enough information from this bug to assist unfortunately.  We're reachable on Discord as well: https://discord.gg/shorebird.

https://docs.shorebird.dev/uninstall is also available should you need it.  Best of luck!

**Comment by blk-raffy** [comment]
We have made further investigation:
Basically if you make the release with a x.x.x version of shorebird and you create a patch with another version of shorebird, like x.x.x+1, the patch will break the release apk by slowing it or breaking it completely (Black screen and so on).
We don't know if somethings has changed about how the patches are applied in the latest shorebird release. Problem solved.

I suggest to write into the documentation that users' should recreate the release version of their app whenever they update shorebird

**Comment by eseidel** [comment]
Hmm, that would certainly be unexpected  `shorebird` is decoupled from the underlying `flutter` (that's how `shorebird flutter version` works): https://docs.shorebird.dev/flutter-version. It's absolutely required that an app use the same flutter version for updates (but shorebird enforces that) and it shouldn't matter to use the same `shorebird` version.  In general we recommend always using the latest `shorebird` and it will automagically use the correct `flutter` to match the `flutter` your app was released with.
