### ISSUE TITLE
Patch and release commands should run `flutter pub get`

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1627]
Not high priority, but it's reasonable for customers to expect this and there's been at least one report of a customer being surprised that `flutter pub get` was not part of the release/patch workflow.

**Comment by codesculpture** [comment]
These are the things come to my mind

1. This could happen if someone made a quick change and dint tested locally, then do release or patch.

I dont think it could be acceptable, since `flutter build` wont do this, i believe.

2. I believe shorebird may became a CI tool so, `flutter pub get` would automatically run through the workflow, so there is no need to run that again from the shorebird side


Conclusion: I somewhat suggest to don't support this, since updating dependencies needs to be done from the user concern. And dont really see any valid reason to do that. 🤷

We can see is there any valid reasons from user though.

**Comment by eseidel** [comment]
Closing for now, since we're a drop-in replacement for `flutter build` and `flutter build` doesn't do this.
