### ISSUE TITLE
Record command line arguments with releases and patches for debugging purposes

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#1664]
This will make it easier for us to debug when something goes wrong and generally provide better support. This could be in the DB or queryable logs.

**Comment by felangel** [comment]
Thoughts on including the args in our logs and getting the info from the admin dashboard via queries instead? It feels wrong to store that in the DB since it's just for debugging purposes?

**Comment by bryanoltman** [comment]
That's probably a better approach. I'll update the issue title to be more problem-focused

**Comment by eseidel** [comment]
My other comment would be that if we do this we should store option/flag names only, and only based on an inclusion list.  In general we do not want to keep any customer data we don't have to.  Otherwise sounds like a good idea, since knowing if a patch was created with "--force" for example can explain certain failures.

**Comment by eseidel** [comment]
We have some of this infrastructure now.  However I would recommend we not record arbitrary paths or command line options, as those might contain things the developer would not want stored with their account on our servers.
