### ISSUE TITLE
fix: sync* is slower with shorebird than stock flutter release builds

### ISSUE THREAD

**Issue by synapsecode** [shorebirdtech/shorebird#1731]
App ID: e7fc7ff5-a045-4ebd-b155-256f12dc70f0

**Description**
I upgraded my application to the latest version of shorebird in order to try out the ios-beta and I must say, the ios beta is far better than the ios-alpha. great work by the shorebird team.
However, I am still facing certain scenarios where the application comes a halt, lags for 5-8 seconds and then becomes functional again. 
This does not happen in regular ios builds so I am sure its a shorebird issue
please note, This happens in the unpatched build created using ```shorebird release ios --force```

**Shorebird Versioning Information**
```bash
shorebird --version
Shorebird 0.25.2 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.16.9 • revision 771d07b2cf97cf107bae6eeedcf41bdc9db772fa
Engine • revision e898854017610e9803e97d0847cc84c7da6822e0
```

**Steps To Reproduce (scenarios where this happens)**
1. Image Cropping using package:image/image functions(decodeImageFile, copyResize) etc
2. when a lot of network images are loading simultaneously (Eg: a social media feed)
3. using package:palette_generator  PaletteGenerator.fromImageProvider(...)
I suspect that anything dealing with native code is experiencing slowdown? would that be a correct assumption?

**Expected Behavior**
It was mentioned that in ios-beta, only the patched app performance is lower than expected, so i expected that the unpatched version should work with the same speed as a regular ios build. while this is true generally, in certain scenarios like the ones mentioned above, it slows down.

**Additional Context**
- slowdown occurring in unpatched build
- already on latest version

**Comment by eseidel** [comment]
Thanks for the report. We wouldn't expect any slowdown from an *unpatched* app.  Will investigate.

**Comment by eseidel** [comment]
Notes:
e7fc7ff5-a045-4ebd-b155-256f12dc70f0 at version 1.5.0+10 is for iOS and Android, has no patches at this time and is built with https://github.com/shorebirdtech/flutter/commit/a3d5f7c614aa1cc4d6cb1506e74fd1c81678e68e

e7fc7ff5-a045-4ebd-b155-256f12dc70f0 at version 1.4.20+9 is iOS only, but *does* have a patch and is also built with https://github.com/shorebirdtech/flutter/commit/a3d5f7c614aa1cc4d6cb1506e74fd1c81678e68e

**Comment by eseidel** [comment]
https://github.com/shorebirdtech/flutter/commit/a3d5f7c614aa1cc4d6cb1506e74fd1c81678e68e is from December 10th and is not the latest Flutter.

https://github.com/shorebirdtech/shorebird/blob/v0.25.2/bin/internal/flutter.version points to https://github.com/shorebirdtech/flutter/commit/a3d5f7c614aa1cc4d6cb1506e74fd1c81678e68e

This isn't the user's fault, I think this is just confusion caused by our `flutter versions use` which we're removing in our release today and hopefully will avoid this issue in the future.

@synapsecode I think if you run `flutter versions use 3.16.9` and release again you'll find unpatched builds run at full speed.  Let us know if that's not the case.  We're also about to release a new version (in about an hour) that will fix one more iOS crasher.

**Comment by eseidel** [comment]
I believe https://github.com/shorebirdtech/shorebird/issues/1687 will prevent future confusion like this.

Please let us know if `flutter versions use 3.16.9` does not resolve the slowdown.   We'll also be shipping 3.19.0 as soon as Flutter does:  https://github.com/shorebirdtech/shorebird/issues/1723

**Comment by synapsecode** [comment]
thank you for the quick response, 
the solution you have DID NOT work

here's what I did:
1. flutter clean && flutter pub get
2. shorebird flutter versions use 3.16.9
3. shorebird build ios
4. opened the .xcarchive in xcode and clicked on distribute app
5. selected adhoc and generated ipa
6. put ipa into diawi, got link
7. deleted the old app on device
8. installed the app using the new link

still same issue persists,
there is a slowdown that grinds the app to a halt, takes 4-5 seconds to recover and then works again
a lot of random freezes

any thoughts on what might be happening?

**Comment by eseidel** [comment]
Since the build was created with `shorebird build` rather than `shorebird release` I have no way to validate which version of Flutter was used to produce is, since the build metadata is never stored with your account.  Although we talk about `flutter` changes as part of our `shorebird` release, and `shorebird` does set the *default* version of Flutter to use, it is possible to end up releasing with different versions of Flutter's engine even with the newest Shorebird releases.   The first thing I'd want to confirm is what version of the Flutter engine (via Shorebird) was used to produce the build, since it could be possible that `shorebird build` was using an older flutter version.

But the easiest way to know if you're using our latest engine (which I would expect to not have performance issues) is to upgrade to the latest shorebird (and flutter) via `shorebird upgrade`

**Comment by synapsecode** [comment]
I'm so sorry, i mistyped it.
I actually used shorebird release ios 

will upgrade shorebird later today. i'll let you know if that fixes the issue

**Comment by synapsecode** [comment]
Hi, Upgraded local flutter and shorebird

the issue still PERSISTS

**shorebird versioning**
```
Shorebird 0.26.0 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.19.0 • revision 8679396700d040e779463461c7c79ba08d130209
Engine • revision 62fa4e8bb30f56eb658989d3e6a982cb787d79d6
```

**flutter versioning**
```
Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bae5e49bc2 (2 days ago) • 2024-02-13 17:46:18 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1
```

steps taken:
1. flutter clean && flutter pub get
2. shorebird release ios --flutter-version 3.19.0       
3. Open xcarchive in Xcode and click on distribute app
4. Select adHoc and get ipa & generate diawi link
5. Installed on phone

**video demo**
NORMAL BUILD: https://bit.ly/cz-flutter
SHOREBIRD BUILD: https://bit.ly/cz-sbexample

as you can see in the Shorebird Build, there is a sudden halt and in the profile screen, simple things like the 3 dots animation stops working. everything freezes.

no such thing happens in the normal build.

**Comment by eseidel** [comment]
Thank you!  We will investigate.

**Comment by eseidel** [comment]
Wow, just watched the videos.  That's very much not expected.

**Comment by eseidel** [comment]
It's hard for me to guess from those videos what might be causing the slowdown.  I think we will need to try and find a similar Flutter app that we can reduce to try and understand what code is hanging.  We could also produce "profile" builds of Shorebird which could be run with the Dart profiler on which might tell us more about where it's spending time.  It also might be possible with "print" debugging to figure out where the slowness is happening.

Our iOS beta generally runs all Dart code on the CPU.  However it does some work to jump from C++ to Dart on the CPU (bouncing through our interpreter).  So it is possible that there are code paths which repeatedly try to jump from C++ back to Dart.  I wonder if there is one such codepath in the http loader or image decoder, since the hangs appear to relate to loading images/videos?  We have plans to remove this unnecessary "bounce" through our interpreter, but it hasn't been a problem so far so we've left it for now.

I'm curious, are you using any plugins which relate to http or image loading/decoding?

**Comment by synapsecode** [comment]
Yes we are using a few plugins in our application
To display images we are using the usual Image.network(...) method
while displaying images, we use this to determine the image size (for aspect ratio calculation)
```dart
import 'dart:ui' as ui;
Future<Size> _getImageSize(Image image) async {
    Completer<ui.Image> completer = Completer<ui.Image>();
    image.image
        .resolve(const ImageConfiguration())
        .addListener(ImageStreamListener((ImageInfo image, bool _) {
      completer.complete(image.image);
    }));
    ui.Image info = await completer.future;
    int width = info.width;
    int height = info.height;
    final sz = Size(width.toDouble(), height.toDouble());
    // log('RECEIVED IMG SIZE => $sz');
	return sz;
}	
``` 

additionally, on the profile page we use this function to get the overall color
```dart
import 'package:palette_generator/palette_generator.dart';
PaletteGenerator.fromImageProvider(...)
```

also, in the app, cropping had a crippling slowdown (~15 seconds)
```dart
import 'package:image/image.dart' as img;
img.Image? originalImage = await img.decodeImageFile(media.path)!;
img.Image croppedImage = img.copyCrop(
  originalImage,
  x: -(tX.toInt() * xF).toInt(),
  y: -(tY.toInt() * xF).toInt(),
  width: (sz.width * xF).toInt(),
  height: (sz.height * xF).toInt(),
);
img.Image resizedImage = img.copyResize(
  croppedImage,
  width: dims.width.toInt(),
  height: dims.height.toInt(),
  maintainAspect: true,
);
```

I'd love to create a minimum reproducible example
but right now, the apple account that I'm using is not mine so not sure if i'll be able to create it

If possible, i'll do it.

**Comment by eseidel** [comment]
This is extremely helpful, thank you.

**Comment by eseidel** [comment]
The next steps here are for someone to take one of the examples listed above and see if they can reproduce the slowdown.  Once we have an example which is slower in our Dart rather than stock Dart, we can profile and speed it up (I have ideas of what it could be, but until we see the profile we won't know).  I don't expect this will be hard to fix once we have a reproduction.  I've added this to our 1.0 milestone for investigation at least.

**Comment by synapsecode** [comment]
Hey!
Found some time to create a simple demo and I was able to reproduce the issue

Github Repo: https://github.com/synapsecode/sbslowtest

shorebird app id: ```c3c94c22-2fe0-468b-aeed-7dccf476719c```

Steps:
1. created the project using flutter 3.16.9 (thats what i had done in the original example)
2. changed flutter version locally to 3.19.0 and ran pub outdated and pub upgrade
3. changed flutter version to 3.19 in vscode and wrote the example
4. created a normal build ```flutter build ipa --release --export-method ad-hoc``` > upload ipa to diawi
5. created a shorebird build
		```shorebird release ios --flutter-version 3.19.0``` > open xcode > distribute app > adhoc > upload to diawi
6. install on phone from diawi link (iPhone 11) 

The Regular Version was smooth and did not experience any freezes

The Shorebird Version a sudden slowdown (the loaders freeze and you cannot scroll for 1-2 seconds)
This was in the UNPATCHED app


I hope this helps! 
I Would love to push to the store with shorebird enabled!

**Comment by eseidel** [comment]
Thank you very much!

**Comment by synapsecode** [comment]
Hi, any update on this issue?

**Comment by eseidel** [comment]
No update.  Felix has been working on a big speed win for iOS patches, Bryan has been finishing adding Azure login and I've been hiring.  It's on our list to look soon, but haven't gotten to it yet. https://github.com/orgs/shorebirdtech/projects/18/views/1

**Comment by eseidel** [comment]
Thanks for the report!  We've confirmed and are investigating.

**Comment by bryanoltman** [comment]
Thanks for sharing the github repro – it has been enormously helpful. It looks like https://pub.dev/packages/palette_generator isn't playing nicely with our Dart fork, and we're working to fix this. The primary cause seems to be a synchronous generator (`sync*`) that yields for every pixel in the image it's processing. This seems to be slower when the generator function is complex (e.g., if it contains a large number of bitwise operations), but we see a substantial slowdown even if the generator function simply yields with no math involved at all.

Thanks again, and we're on it

**Comment by eseidel** [comment]
The bug here is in how we handle "resume" for sync* (and async/async* more generally) that we always force the code to jump back to the simulator, even if the original "suspend" came from the cpu and could continue on the cpu.  This is because the suspend state doesn't currently contain any information about what context we should resume on.

Probably the right fix is to modify SuspendState to carry this one extra bit of information.  We also might be able to fix by changing the resume to do a lookup with the LinkOracle, but I suspect the SuspendState fix is much better, just might require us modifying the layout of SuspendState.

Shouldn't take very long to fix, just requires a bit of staring at the SuspendState code.

**Comment by eseidel** [comment]
With us busy getting 1.0 out the door, we may not get to this for a couple weeks.  But we know pretty much what we need to do when we do get to it.  Thank you again for the report and reduction!

**Comment by synapsecode** [comment]
you're welcome! Would love to use shorebird in production soon!, thanks.

**Comment by eseidel** [comment]
This is our last remaining bug blocking 1.0.  Felix and I discussed this evening and have a plan which he plans to execute tomorrow.

Basically we plan to change AllocateSuspendStub to call a new method to determine if the passed pc should be run on the simulator or the cpu (can just look up the Code object for the PC and see which table it's in?). We may also want to (possibly later) change Code object to carry this information rather than re-computing, since when we build the Code object we know which PC's it's using (then again, it's also pretty cheap to look it up, it's just comparing the payload_start for the Code object against the two table ranges).

Then we will also change UntaggedSuspendState to steal a single bit from pc (probably the lowest bit) and make the bit 1 if the Code wants to run on the simualtor and 0 if it can run on the CPU.

And then we change call callers that make direct access to SuspendState::pc_offset() to be aware they need to mask away this lowest bit before using the pc.  We also of course change SuspendState::pc() to do the masking for the c++ side.

Then we also need to change the ResumeStub to read out both this bit and the pc, and based on the bit either resume on the CPU or simulator.

That's it 🤷   Hopefully it's about a day of work for Felix, but there might be unforeseen difficulties.  Probably the hardest part is making sure we've found all the places which access the pc_offset?  Presumably all of them use SuspendState::pc_offset() which should make that straightforward?

**Comment by synapsecode** [comment]
hi, my team is preparing for ios launch and we'd love to have shorebird enabled. what's the status on 1.0 ? thanks!

**Comment by eseidel** [comment]
> hi, my team is preparing for ios launch and we'd love to have shorebird enabled. what's the status on 1.0 ? thanks!

This is one of two remaining blocking bugs for 1.0.  We had hoped to launch today, but haven't quite resolved this bug.  (We have a local fix, but it's not complete yet.)  I don't know how long it will take us to resolve this, but my guess is some more number of hours (e.g. we might be able to ship 1.0 tomorrow).  I've filed a tracking bug for 1.0 and we're starting on the remaining chores now: https://github.com/shorebirdtech/shorebird/issues/1855

**Comment by eseidel** [comment]
We've fixed this!  Working on a release now, should be out in a couple hours.

**Comment by synapsecode** [comment]
amazing work by the team! looking forward to the release.
