### ISSUE TITLE
fix: the flutter version of shorebird doesn't support intl 0.19.0 package

### ISSUE THREAD

**Issue by vuzzer** [shorebirdtech/shorebird#1840]
App ID: (e8324c05-0ce2-46b6-ac10-2a6759904d8f)

**Description**

I have changed my channel of flutter to master branch in order to support `intl 0.19.0` package 
The version of flutter of shorebird doesn't support `intl 0.19.0` package.
Building release failed because flutter of shorebird depend on `intl 0.18.1`.

**Steps To Reproduce**

1. change channel of flutter to master and upgrade channel
2. install `intl 0.19.0` package
3. execute `shorebird release android`
4. error: intl is pinned to version 0.18.1 by flutter_localizations from the flutter SDK.

**Screenshots**

My version of flutter compared to the flutter version of shorebird

<img width="1162" alt="Screenshot 2024-03-29 at 00 15 35 1" src="https://github.com/shorebirdtech/shorebird/assets/50607415/48daf60c-6804-44f0-9a00-d2341ce19187">

Error when building a release

<img width="888" alt="Screenshot 2024-03-29 at 00 19 46" src="https://github.com/shorebirdtech/shorebird/assets/50607415/3a3d5df9-767f-4f6e-97ad-9e302f405fab">

**Comment by eseidel** [comment]
Thanks for the report.  `shorebird` currently only supports the latest stable.  At this time that's 3.19.x.  We don't have any plans to add support for other Flutter channels in the near future (although probably eventually will).

**Comment by eseidel** [comment]
Yeah, looks like flutter stable is still on 0.18.1 as you describe:
https://github.com/flutter/flutter/blob/stable/packages/flutter_localizations/pubspec.yaml
Or
https://github.com/flutter/flutter/blob/3.19.5/packages/flutter_localizations/pubspec.yaml
for the perma-link.

Closing for now since we don't plan to support any other channels than stable in the near future.  https://github.com/shorebirdtech/shorebird/issues/1548 is the only other request I'm aware of for non-stable channels.

Thanks again for using Shorebird and sending us a report!
