### ISSUE TITLE
feat: Check if the flutter in the path is supported by shorebird in a release

### ISSUE THREAD

**Issue by erickzanardo** [shorebirdtech/shorebird#1847]
**Description**

In the day to day, developers will be using their flutter installation to work on their app. When doing a release, a flutter installation managed by shorebird will be used instead, and their version might not match.

This can increase the risk of getting inconsistencies between local development builds and release builds.

I suggest that we create a validation in the CLI to check if the flutter on the path is a supported version of shorebird when doing a release, and warning the user in the case that it isn't.

**Requirements**

- [ ] Add a validation in the shorebird CLI to check if the flutter in the path is a supported flutter version by Shorebird

**Additional Context**

We could also be more strict and maybe error the command in case of a mismatch, or maybe leave the warning as a default and add a `--strict` or something like that, flag that would turn the warning into a command error.

**Comment by eseidel** [comment]
I'm not sure if there is more to do here?  I think this is mostly covered by our version management. 

One thing I think we could do to improve our flutter version management is default to the version in the path when making a release instead of the latest included with shorebird.

See also https://github.com/shorebirdtech/shorebird/issues/1385
