### ISSUE TITLE
Question: in depth info of the interpreter for supporting iOS

### ISSUE THREAD

**Issue by modulovalue** [shorebirdtech/shorebird#1871]
Congrats on the (almost) iOS launch!

I wanted to ask if there is any in depth info about the Dart interpreter that you are using for supporting code push on iOS.

In particular, I'm interested in the trade-offs that you had to make and any potential performance implications that they might have. Shorebird seems great, but I can think of many use cases where performance is really important (especially with 120hz refresh rates where the frame budgets are really tight).

Here are some questions that I have:

- will there be support for efficient AOT compiled Dart code that doesn't support code push *and* interpreted Dart code that supports code push at the same time (e.g., something that resembles a WebView but delivers code-pushed Flutter views)?
  * if yes, will there be a way to synchronously (i.e. `X send(Y)` and not `Future<X> send(Y)`) interact between native Dart code and code-pushed Dart code (possibly where the native code expects the code-pushed flutter view to adhere to a specific interface)?

- are there any limitations (e.g., limited isolate support)?

- will the interpreter have to play catch up with the official SDK in terms of performance? Consider, for example, this talk by Slava: https://www.youtube.com/watch?v=jV2Zx3hjHPc which showcases some minor recent performance optimizations. Will shorebird have to reimplement any work like that, or is shorebird able to reuse significant parts of the SDK infrastructure and is able to benefit from non-VM-related performance optimizations?

It's not urgent. Some document that eventually answers these questions (and hopefully more!) once you find the time to write things down would be good enough for me.

**Comment by eseidel** [comment]
Hi.  Thanks for the issue.  I'm actually in the middle of a "how shorebird works" article, so will try to answer some of these questions there.

> Shorebird seems great, but I can think of many use cases where performance is really important (especially with 120hz refresh rates where the frame budgets are really tight).

Shorebird is designed to have 0 effect on your "release" builds, and your "patch" builds are designed to only interpret changed code.  All unchanged code should run at full speed.  So long as you don't try to patch the hottest loop in your 120hz game, even patched versions should be imperceptible to the user.

> will there be support for efficient AOT compiled Dart code that doesn't support code push and interpreted Dart code that supports code push at the same time (e.g., something that resembles a WebView but delivers code-pushed Flutter views)?

That's how it works.  There is no trade-off.  All Dart code in your application is compiled normally in a "release". Only when you make changes and create a "patch" is the interpreter used, and then it's only used for the changed code.   Typically when an app changes, even if they had to make large changes to the app, the performance is unaffected, since the core flutter framework (which contains all the really hot code paths) remains unchanged, and thus runs on the CPU at full speed out of the signed release binary on the device.

> if yes, will there be a way to synchronously (i.e. X send(Y) and not Future<X> send(Y)) interact between native Dart code and code-pushed Dart code (possibly where the native code expects the code-pushed flutter view to adhere to a specific interface)?

Shorebird just does this automatically. :). That's the magic.  The hard part (and why it took us 9 months) has been to make this seamless.  We're mostly there.  Good enough to call 1.0.  There are still a few types of changes in patches which can confuse our "linker" into thinking it can't use the "release" / AOT versions of functions and instead runs the interpreter version when it shouldn't.  The most common case we're aware of is adding and removing classes, but we'll have that fixed soon after 1.0 launch.   See https://docs.shorebird.dev/status.

> are there any limitations (e.g., limited isolate support)?

I'm not aware of any kind of Dart code we can't update with Shorebird.  The system is designed to be "pay as you go" (not in a money sense) in the sense that you should only have to "pay" (by having the code run slower) for changed code, unchanged code should run unmodified, full speed on the CPU.

https://docs.shorebird.dev/faq#what-cant-we-use-shorebird-code-push-for talks about some of the app store restrictions about how we don't/can't change "native" code.

Shorebird is sorta like if you ran your entire app inside a WebView, except that WebView were actually fast. 🤷 

> will the interpreter have to play catch up with the official SDK in terms of performance? Consider, for example, this talk by Slava: https://www.youtube.com/watch?v=jV2Zx3hjHPc which showcases some minor recent performance optimizations. Will shorebird have to reimplement any work like that, or is shorebird able to reuse significant parts of the SDK infrastructure and is able to benefit from non-VM-related performance optimizations?

We use a fork of the VM.  So far we've not had to turn off any performance optimizations in the VM to make Shorebird work.

Hope that helps!

**Comment by modulovalue** [comment]
Thank you @eseidel. My mental model of what you were trying to do was very wrong. Shorebird sounds even better now.

Thank you for the answers, they have answered all the questions that I had.
