### ISSUE TITLE
fix: patch created with wrong snapshot version

### ISSUE THREAD

**Issue by chetanApnaklub** [shorebirdtech/shorebird#1894]
App ID: `0a08c1df-3a32-4d30-b8ce-40d62ef55c8f`

**Description**

faced a strange issue where the patch was causing the app to crash on opening, we had done patch updates in the past but have not faced this issue. Unfortunately have to deactivate the patch.

We do not have actual logs It happened to some ground users and the patch rollout was too slow. Fortunately received mail from the play console where I can find the logs 

`[FATAL:flutter/runtime/dart_vm_initializer.cc(89)] Error while initializing the Dart VM: Wrong full snapshot version, expected '<<SOME ID>>' found '<<Another ID >>`

Even these crashes are not logged on to the Firebase crashlytics 

Same scenario I tried today on the development environment creating the same release and providing the same patch and now it works and this time rollout was also quick.

Here is the result of `shorebird doctor` 

```
Shorebird 0.18.2 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.13.9 • revision 39df2792f537b1fc62a9c668a6990f585bd91456
Engine • revision e81fa131e59506d9f6af2a0cee7de749131f1bf0

✗ Shorebird is up-to-date (0.6s)
  [!] A new version of shorebird is available! Run `shorebird upgrade` to upgrade.
✓ Flutter install is correct (0.2s)
✓ AndroidManifest.xml files contain INTERNET permission (36ms)
✓ Has access to storage.googleapis.com (44ms)
```

**Comment by eseidel** [comment]
Thank you for the report.  This is definitely unexpected.  We'll look more from our side shortly.

**Comment by chetanApnaklub** [comment]
Sure, please keep me updated on the exact cause of the issue and what can be done to prevent it in the future when the next patch is released.

Most probably, the next patch release would be done from our side after knowing RCA.

**Comment by eseidel** [comment]
This message should only happen when the version of Dart differs between the snapshot (e.g. patch) built and the libflutter.so (dart vm) trying to run the patch/snapshot.  This happens for us when we're doing our own local testing, but I'm very surprised to hear about this happening in the wild.  Our `release` command records the exact flutter hash that was used during building, and then the `patch` command downloads that exact flutter hash and uses that for patching.

There was briefly bug a couple weeks ago where one version of `shorebird` reported the the wrong version during `release`, maybe your release happened to have been built with that exact version and thus further patching was broken?

**Comment by eseidel** [comment]
The bad release was 0.26.6, fixed in 0.26.7:
https://github.com/shorebirdtech/shorebird/blob/main/RELEASE_NOTES.md#0267-march-18-2024

**Comment by eseidel** [comment]
@felangel managed to find the bug and reproduce just now.  He's working on a fix. 

The problem occurred due to having created a release from both iOS and Android with different Flutter versions.  Our server only stores a single Flutter version with a Release, and failed to check that later platforms added to that Release had the same exact Flutter version.  So in this case, 8.3.0+298 for iOS was created a couple hours before 8.3.0+298 for Android.  Android used a different version of Flutter, the tool (incorrectly) allowed this.  When a patch was later created for the Android release, it used the (wrong) Flutter version from the iOS Release as the basis for creating the patch, thus then later failing when trying to load the patch into the Android release.

We'll have a fix out shortly so no one else ever hits this.

We've also filed several bugs against other components to track ways that we could have caught/prevented this (some are in our private Dart fork, so the links wont work, but including here for completeness):
* https://github.com/shorebirdtech/engine/issues/79
* https://github.com/shorebirdtech/_shorebird/issues/626
* https://github.com/shorebirdtech/_shorebird/issues/1686

**Comment by eseidel** [comment]
GitHub automatically closes the issue as part of us landing the fix.  I'll send you all and email shortly with my notes from our call.  We expect to ship this (and other fixes) to all users later this afternoon.  Thank you again for bringing this to our attention!
