### ISSUE TITLE
fix: `detecting release version` hangs for a long time (downloading assets)

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#1899]
This has confused many customers.  We don't explain that we're downloading Flutter assets.

One fix might be to just run `flutter precache` in its own separate step.

See 
https://discord.com/channels/1030243211995791380/1229355551868321874
as on example.

**Comment by bryanoltman** [comment]
FWIW, "Detecting release version" is slow when Shorebird's cache (not Flutter's) is downloading artifacts (specifically [here](https://github.com/shorebirdtech/shorebird/blob/main/packages/shorebird_cli/lib/src/shorebird_release_version_mixin.dart#L12)). 

This particular issue wouldn't be solved by `flutter precache`, although precaching Flutter artifacts when a new version of Flutter is installed is a good idea – the first call to `flutter build` after installing a new version of Flutter takes a long time because assets are silently being downloaded).

**Comment by bryanoltman** [comment]
Looking into this. We just need to be careful to not cross `logger.progress` streams

**Comment by eseidel** [comment]
<iframe src="https://giphy.com/embed/3o72FiKtrMAjIb0Rhu" width="480" height="201" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/ghostbustersmovies-ghostbusters-original-3o72FiKtrMAjIb0Rhu">via GIPHY</a></p>
