### ISSUE TITLE
feat(shorebird_cli): `shorebird build apk --flutter-version=3.19.6`

### ISSUE THREAD

**Issue by vuitv** [shorebirdtech/shorebird#2145]
feat(shorebird_cli):  add flag on `shorebird build apk --flutter-version=3.19.6`

**Comment by bryanoltman** [comment]
Can you share why you're wanting to use `shorebird build apk` and not `shorebird release android --artifact=apk`?

**Comment by vuitv** [comment]
I built the release version with shorebird release android and published it on the store, and now I want to have an additional apk version to upload to my website.

**Comment by eseidel** [comment]
Shorebird assumes that a version number corresponds to an exact binary.  Or in the case of .aab files, to the exact .apk files produced from that aab by the stores.  Building a second time from source risks introducing accidental changes which could cause later patches to be invalid (since they depend on being able to do a binary diff with the original released compile dart code).

If you'd like to download the saved .aab you can do so from https://console.shorebird.dev/.  We don't yet provide an out-of-the-box tool to turn an .aab into an apk.  `shorebird preview` knows how to do that under the covers, or it's also possible with bundle tool directly: https://github.com/google/bundletool/. We should probably provide a way to download architecture-specific APKs since that's not an uncommon request.

**Comment by vuitv** [comment]
Thanks for the support, maybe I should make a note to use `shorebird release android --artifact=apk` for the next release

**Comment by eseidel** [comment]
I think that will work better for you, yes.  Thanks!
