### ISSUE TITLE
fix: AOT files linking failure

### ISSUE THREAD

**Issue by Oladips** [shorebirdtech/shorebird#2161]
**Screenshots**
<img width="669" alt="Screenshot 2024-05-28 at 14 03 18" src="https://github.com/shorebirdtech/shorebird/assets/45954324/cef6f7b2-7e38-4c4c-b647-59cec9dbe134">

I'm trying to patch my IOS app and I'm getting this AOT files linking error.

**Comment by erickzanardo** [comment]
Hey can you try deleting shorebird's cache folder and trying again? I noticed this happening in some cases where the cache got corruped or incomplete.

You should be able to achieve that by running `shorebird cache clean`

**Comment by Oladips** [comment]
I did this and it's still giving the same error

**Comment by eseidel** [comment]
"wrong full snapshot version" probably means that analyze_snapshot is trying to work with a snapshot not created from the same version of Dart.  But that shouldn't be possible, since our code in `shorebird patch` intentionally uses the exact same version of Flutter (and thus Dart) that was used during `shorebird release`.  This might suggest we have a bug in that logic?

Unfortunately the "snapshot version" presented isn't actually a git hash, but rather a hash of the snapshot reading file inside the dart SDK, so there isn't a good way to look up which versions it's mis-matching.

However we should be able to pull the flutter information from the release and try the corresponding analyze_snapshot to see if somehow we might have recorded the wrong flutter version with the release, or alternatively if the bug is in `shorebird patch` that it's pulling down the wrong flutter version when building the patch.

**Comment by eseidel** [comment]
Could you please share your app_id?  It's the number in shorebird.yaml and will allow us to find your release binaries in our backend storage for comparison.  https://docs.shorebird.dev/faq/#do-i-need-to-keep-my-app_id-secret

**Comment by Oladips** [comment]
app id: 802410a9-2b63-486b-bb6a-d314c94075fb
-- flavor
      prod: 70f58f3e-115c-4732-9027-354319eb0a44

Here's the app ID and the prod flavor id

**Comment by eseidel** [comment]
This appears to be the app https://admin.shorebird.dev/apps/70f58f3e-115c-4732-9027-354319eb0a44 (internal link).

The most recent release was made on May 21st: https://admin.shorebird.dev/apps/70f58f3e-115c-4732-9027-354319eb0a44/releases/56593.  I'm not sure which release was attempted to be patched.  Regardless all four of the most recent releases are using https://github.com/shorebirdtech/flutter/commit/47571af6a3acdebedf88255099ff1de1c3324049 (3.19.5).

**Comment by eseidel** [comment]
That screenshot is clearly running analyze_snapshot_arm64 from a path with 47571af6a3acdebedf88255099ff1de1c3324049 in it, suggesting that probably somehow the release was incorrectly tagged with the wrong Flutter version?

**Comment by eseidel** [comment]
One thing we could try is pulling the release to one of our machines and running analyze_snapshot from 47571af6a3acdebedf88255099ff1de1c3324049 on it and seeing if they match.

Another debugging tool we could build is to write a small script (and run it against our various flavors of dart) to create a mapping between snapshot version and dart version, filed https://github.com/shorebirdtech/shorebird/issues/2182

**Comment by eseidel** [comment]
If you haven't already a `shorebird clean` would resolve the issue if somehow the analyze_snapshot you have on disk doesn't match the one expected by 47571af6a3acdebedf88255099ff1de1c3324049.

Otherwise I suspect there isn't much you can do, other than creating a new release (possibly with a more recent version of Flutter), since otherwise this is a bug in our code and we'll need to fix it.  Either way it's likely you'll need to make a new release to benefit from the fix.

**Comment by eseidel** [comment]
I think the right solution is to re-release with a later Shorebird/Flutter version.  We've made sooooo many improvements to our code in the last 2 months and it's unlikely to be the right call to investigate this older release further at this time.

Thank you again for the report!
