### ISSUE TITLE
fix: iOS releases are not supported with Flutter versions older than 3.19.5.

### ISSUE THREAD

**Issue by leonidtimo17** [shorebirdtech/shorebird#2202]
App ID: ad4d2d2d-7e1c-4fac-875e-dc129562ad1b

**Description**

When building release version with flutter version 3.16.9 for iOS occurs error: "iOS releases are not supported with Flutter versions older than 3.19.5.". On android everything works fine.

**Steps To Reproduce**

1. shorebird release ios --flavor cscartmp --flutter-version=3.16.9

**Additional Context**

```
user@macbook flutter-project % shorebird doctor
Shorebird 1.1.9 • git@github.com:shorebirdtech/shorebird.git
Flutter 3.22.1 • revision 2f366bd7c9cdb59a1231fdb13c985be48f47149b
Engine • revision e5fdf87c8fa18e584204987de09e6d86f462c87c

✓ Shorebird is up-to-date (2.0s)
✓ Flutter install is correct (0.9s)
  [!] The version of Flutter that Shorebird includes and the Flutter on your path are different.
        Shorebird Flutter: 3.22.1
        System Flutter:    3.16.9
      This can cause unexpected behavior if you are switching between the tools and the version gap is wide. If you have any trouble, please let us know on Shorebird discord.
✓ AndroidManifest.xml files contain INTERNET permission (0.1s)
✓ Has access to storage.googleapis.com (0.8s)
✓ shorebird.yaml found in pubspec.yaml assets (26ms)
1 issue detected.
```

**Comment by eseidel** [comment]
This is unfortunately "works as intended".  We used to support back to 3.16.9, but we found various crashers in some of those early preview builds of our iOS support and thus have since disabled those builds.   We currently only have bandwidth to support the latest stable Flutter version (which at time of writing is 3.22.1).  Hopefully in the future we will be able to support back-porting changes to older Flutter versions.  Thank you for trying Shorebird!

**Comment by leonidtimo17** [comment]
Thanks. Documentation probably should be updated

**Comment by eseidel** [comment]
Will make sure to check tomorrow, thanks!

**Comment by eseidel** [comment]
Updated: https://github.com/shorebirdtech/docs/commit/df2e00d9a5807f41ae4a8f1bd373bbf7bcc3962f. Thanks for the report!
