### ISSUE TITLE
feat: help debugging build times (hangs?)

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#2211]
A user reported via discord a very long iOS build time:
`Is it normal for it to take this long the first build on a new project? At 40+ minutes. I don't remember my other project taking close to this long for the first build. On an m1 machine.`
![image](https://github.com/shorebirdtech/shorebird/assets/478541/b9acf59b-d451-40ef-bd88-96e89208557f)

Reported that `-v` did not change the output, it just hung again.

https://discord.com/channels/1030243211995791380/1030243213002412164/1249847923886522498

We need better debugging tools to help such users.

**Comment by eseidel** [comment]
Customer reports the problem went away after restarting their terminal.   Guess we still need better debugging tools here.

**Comment by erickzanardo** [comment]
Probably related to #2160?

**Comment by erickzanardo** [comment]
@eseidel in the last days, we landed a couple of PRs that will help on this.

The only open referenced issue to this one it 2043, but that is a legit possible issue, and the idea is that everything that was landed here will help solve that issue.

So I believe we should close this one and track the remaining efforts on #2043? What do you think?

**Comment by bryanoltman** [comment]
Reopening because I don't know that our work here is done. A customer reported long build times on CI where they don't have access to logs. I think the solution may be to selectively print some of Flutter's output, eg when it's installing artifacts.

Discord link: https://discord.com/channels/1030243211995791380/1253464055994388490

**Comment by bryanoltman** [comment]
A report of the xcrun archive command hanging (probably not caused by us, but an example of something that might be helpful to surface https://discord.com/channels/1030243211995791380/1250070546008379423/1253850773574647881)

**Comment by erickzanardo** [comment]
I some testings, which produced better and more reliable measurements:

```
Shorebird release: 59923 (discarded), 37775, 37093 = 37434
Plain flutter: 154772 (discarded), 35695, 34817 = 35246

Run two:
Shorebird release: 60167 (discarded), 38004, 37091 = 37547
Plain flutter: 150762 (discarded), 37573, 35694 = 36633
```

I made two CI runs, 3 builds with Plain flutter and 3 builds through Shorebird release. These numbers are times in milliseconds  regarding **only** how long the `flutter build appbundle` command too.

I discarded the first (and worsts) times because there is a lot of flutter tool caching and setuping happening in the first run.

I feel our Flutter doesn't add build time in comparison to plain flutter, since the difference is so small.

So I would say that the answer to the question: "Does Shorebird's Flutter takes longer than official Flutter to build?" is "No". 

It seems to me, that most cases the feeling of "shorebird's build takes longer" than flutter due to how shorebird's logs and progresses are presented.

When inspecting the verbose log of the `flutter build appbundle`, We noticed that gradle downloading its dependencies, in combination with all the installations of the android SDK, takes several dozen seconds of the build, which adds a lot to the total build, making it looking that the compilation is taking longer than it actually is.

---

This is just a status report on the checkpoint of the investigation that I got. I will be working now on trying to make shorebird's cache management, and progress logging better to improve user experience.

**Comment by erickzanardo** [comment]
> When inspecting the verbose log of the flutter build appbundle, We noticed that gradle downloading its dependencies, in combination with all the installations of the android SDK, takes several dozen seconds of the build, which adds a lot to the total build, making it looking that the compilation is taking longer than it actually is.

This happens even when `flutter precache` is executed beforehand.

**Comment by bryanoltman** [comment]
>  I will be working now on trying to make shorebird's cache management, and progress logging better to improve user experience.

It might be good to spell out specific steps you're taking, probably as a small number of github issues with clear resolution criteria.

**Comment by erickzanardo** [comment]
@bryanoltman Linked two proposals above.

**Comment by felangel** [comment]
The customer reported that restarting the terminal resolved this issue:
> Quick update on this - I ended up restarting my terminal and it worked after that. Before that I ran shorebird init then shorebird doctor then shorebird release android without ever restarting terminal and it was stuck.

**Comment by eseidel** [comment]
Closing based on customer feedback.
