### ISSUE TITLE
Add a --allow-broken-flutter or similar to disable flutter version check.

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#2222]
A customer has (understandably) asked to be able to choose if they wish to update their existing iOS apps using Shorebird, even though we now know all previous releases made with Shorebird have https://github.com/shorebirdtech/shorebird/issues/1986

**Comment by felangel** [comment]
Would the proposed flag allow users to release to any Flutter version (e.g prior to 3.19.5)?

This seems like a big liability for us and is not worth doing imo because users will likely not know whether they are affected by the bug and the repercussions can be severe. The right solution imo is to back-port the fix.

**Comment by eseidel** [comment]
I don't think we can provide a reasonable behavior here.  I'm just going to apologize to customers.

I think our only real option would be to revert the restriction PR.

Is it possible for customers to stay on an older version of Shorebird still?  I don't think so (I think we force upgrade these days).
