### ISSUE TITLE
unable to build release for ios

### ISSUE THREAD

**Issue by aloRanking** [shorebirdtech/shorebird#2379]
App ID: bd67c34c-c2a6-413d-b7bf-32024db04d8a

**Description**

I tried to create an iOS release using the Codemagic platform (yaml), but i keep getting

"The project has flavors (ImageNotification), but no --flavor argument was provided

If you aren't sure why this command failed, re-run with the --verbose flag to see more information."

I keep getting this error after i upgraded my shorebird and flutter(3.22.2).

this what i have in my shorebird.yaml:
app_id: bd67c34c-c2a6-413d-b7bf-32024db04d8a
flavors:
  ImageNotification: d11e77e1-2a43-4d49-9934-55064970570a

the commands that i tried in yaml file:
1. shorebird release ios
2. shorebird release ios --flutter-version 3.22.2 -- --export-options-plist=/Users/builder/export_options.plist

 I don't know if i need to add any argument to the command.

Thank you.

**Comment by bryanoltman** [comment]
It looks like you hit a bug when initializing shorebird that we've since fixed (we were incorrectly recognizing notification schemes as flavors https://github.com/shorebirdtech/shorebird/issues/1703). This has been fixed, and you can update your shorebird yaml from:

```yaml
app_id: bd67c34c-c2a6-413d-b7bf-32024db04d8a
flavors:
ImageNotification: d11e77e1-2a43-4d49-9934-55064970570a
```

to

```yaml
app_id: bd67c34c-c2a6-413d-b7bf-32024db04d8a
```

And this issue should resolve. Sorry for the inconvenience!

**Comment by aloRanking** [comment]
Thank you boss!
