### ISSUE TITLE
feat: expose text/accessible information about patch downloads and installs

### ISSUE THREAD

**Issue by orestesgaolin** [shorebirdtech/shorebird#2652]
**Description**

Would be convenient to have a textual representation of the following statistics:

- number of patch downloads per patch: total and per day
- number of patch installs per patch: total and per day

This could be a tabular information or just a simple label below the chart.

![screenshot_20241203_165539](https://github.com/user-attachments/assets/87f29710-eee7-47e7-9449-12f7bd0491b5)

**Requirements**

- [ ] Some form of parse'able and accessible information about installs and downloads of patch available in the console

**Additional Context**

**Comment by eseidel** [comment]
Thank you!

**Comment by eseidel** [comment]
I think Felix started this but we got busy with other things.  Moving this back to the backlog.

**Comment by felangel** [comment]
@eseidel about to open a PR it was quick

**Comment by felangel** [comment]
@orestesgaolin just deployed the changes. Let me know what you think, thanks!

Sample:
![Screenshot 2024-12-18 at 3 12 46 PM](https://github.com/user-attachments/assets/5c40cc93-95fc-40ce-bceb-85b5c60a3859)

**Comment by orestesgaolin** [comment]
Thanks, this is much easier to get a general sense now.

One oddity that I spotted is that the number of today installs is bigger than number of downloads. Is that because there may be some users from previous days that have installed the patch just today?

![screenshot_20241218_223144](https://github.com/user-attachments/assets/2b2866c8-aa4a-4537-b63c-a0029443f003)
![screenshot_20241218_223126](https://github.com/user-attachments/assets/ef70da59-06fd-4c3e-a42e-1f9b87523a5a)

**Comment by eseidel** [comment]
Yeah, "download" means "device reported downloading the patch".  "install" means "device reported back having booted successfully from the patch".

all-time downloads should always be greater than all-time installs.  However the way that we report events is not robust.  If we try and fail to report (e.g. device just lost network connectivity), we won't try again.  And yes, a user can download one day and then install many weeks/months later, so it could easily be the case that installs > downloads the day after a patch for an app used once a day (e.g. many people download the patch day of patch, but don't launch a second time to do the "install" until the day after the patch, when also fewer people are downloading since most got it the first day).

**Comment by eseidel** [comment]
> @eseidel about to open a PR it was quick

Oh!  Sorry, I didn't realize you'd just moved it to "todo" today.  I was just cleaning up the board and assumed this was long ago moved into todo and forgotten.  My bad.
