### ISSUE TITLE
feat: `shorebird` should tell me when there is a new release

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#393]
At least `shorebird doctor` if not other commands.

**Comment by eseidel** [comment]
Oh, nevermind it already does.

```
eseidel@erics-mbp shorebird % shorebird doctor 

Shorebird v0.0.8
Shorebird Engine • revision d470ae25d21f583abe128f7b838476afd5e45bde
✗ Flutter install is correct (6.4s)
  [!] The version of Flutter that Shorebird includes and the Flutter on your path are different.
        Shorebird Flutter: 3.7.10
        System Flutter:    3.7.12
This can cause unexpected behavior if you are switching between the tools and the version gap is wide. If you have any trouble, please let us know on Shorebird discord.
✗ AndroidManifest.xml files contain INTERNET permission (0ms)
  [✗] No Android project found
✗ Shorebird is up-to-date (0.7s)
  [!] A new version of shorebird is available! Run `shorebird upgrade` to upgrade.

3 issues detected.
```

**Comment by OsamaQureshi796** [comment]
Hi @eseidel 
currently I'm using master branch of flutter because of the issue that's been fixed in master branch. I'm getting error that your local flutter and shorebird flutter are different. I've already upgrade shorebird.
![IMG-20230927-WA0001](https://github.com/shorebirdtech/shorebird/assets/58250220/4ed1e99b-a4a8-4583-927c-9a5c28a59130)

**Comment by OsamaQureshi796** [comment]
Hi @eseidel 
currently I'm using master branch of flutter because of the issue that's been fixed in master branch. I'm getting error that your local flutter and shorebird flutter are different. I've already upgrade shorebird.

![IMG-20230927-WA0004](https://github.com/shorebirdtech/shorebird/assets/58250220/eff5ca66-0b56-4811-9178-16a89d28408a)
![IMG-20230927-WA0003](https://github.com/shorebirdtech/shorebird/assets/58250220/8ae9af65-0a21-4fa7-b618-05c5ff39c158)

**Comment by eseidel** [comment]
Yeah, Shorebird only supports the latest stable at this juncture.  We try to release within 24 hours of when Flutter posts a new stable hot fix (which they do every other weds or so):
https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel
