### ISSUE TITLE
[Question]How to setup shorebird_code_push_api

### ISSUE THREAD

**Issue by santoshgistto** [shorebirdtech/shorebird#50]
**Question**
Thanks for this. 
I would like to know how can i setup `shorebird_code_push_api` and test quickly on my local machine. ( i don't see doc around that)
I know still in development but would like to play around.

**Comment by felangel** [comment]
Hi @santoshgistto 👋
We’re moving the api to a private repo in order to allow us to iterate more quickly and not worry about things like secret management.

You can check out the instructions at https://github.com/shorebirdtech/install for the most up-to-date docs on getting started (keep in mind it’s a bit early so we’re not giving out api keys yet).

Another option is to look at https://github.com/shorebirdtech/old_repo/blob/main/updater/UPDATER_DEMO.md for instruction on how to run the early demo on your own devices.

Hope that helps!

**Comment by CicadaCinema** [comment]
> We’re moving the api to a private repo in order to allow us to iterate more quickly and not worry about things like secret management.

Is this just a temporary measure for now?

**Comment by felangel** [comment]
> > We’re moving the api to a private repo in order to allow us to iterate more quickly and not worry about things like secret management.
> 
> Is this just a temporary measure for now?

Yes, our main focus currently is getting an initial version built that folks can try out so we can collect feedback.

**Comment by eseidel** [comment]
Thanks for the issue.  Looks like Felix answered.  As he notes, we may move code in/out of public as needed while we figure out what we're building.  For now we've moved the cloud parts private as they became too complicated to maintain publicly (when we could just check in secrets instead of doing a secret sharing dance) while we're still in these super super early stages.

**Comment by santoshgistto** [comment]
Thank you
