### ISSUE TITLE
fix(shorebird_cli): ipa builds can fail silently

### ISSUE THREAD

**Issue by bryanoltman** [shorebirdtech/shorebird#606]
**Description**

When running `shorebird release ios-preview` or other commands that build an ipa, if the build fails (due to incorrect developer team/cert setup in xcode, for example), the command fails silently. The shorebird command ultimately fails because it cannot find an ipa file, but it's not obvious why that is.

Running the underlying flutter command directly will show more helpful output:

```
Building App Store IPA...                                           5.9s
Encountered error while creating the IPA:
error: exportArchive: Communication with Apple failed
error: exportArchive: No signing certificate "iOS Distribution" found
```

We should communicate this failure so it's obvious what went wrong, possibly just by displaying this output when running the shorebird command.

## Reproduction steps

1. Create a new project with `flutter create`
2. Initialize shorebird with `shorebird init`
3. Open the .xcworkspace in Xcode, assign a development team
4. Run `shorebird release ios-preview`

**Comment by eseidel** [comment]
Yeah, this is a down-side of us hiding `flutter` output behind spinners.  Is that errors like this (which flutter explains in the logs) don't show up.  We could capture `flutter` output and display it on failure, but that my have its own complexities.

It's probably more important for us to wire up the CI integrations and just have our logs always be verbose rather than continue to pretty up our "a human is typing these" UIs we have today.  Not sure?
