### ISSUE TITLE
fix: delete `shorebird build apk`

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#768]
`shorebird build apk` is a footgun, and we should just update our docs to talk more about `shorebird release android --artifact apk`, or possibly even `shorebird release apk`, since it turns out that wanting an APK output is still surprisingly common among our customers.

**Comment by eseidel** [comment]
The reason why it's a footgun, is that people don't understand that `shorebird release android --artifact apk` does the release bits they need and `shorebird build apk` doesn't.   We should rename to `shorebird release apk`, since "android --artifact" are just redundant.

**Comment by eseidel** [comment]
`android` could be an alias to `aab` if we like and `apk` could just be a top-level `release` command?

**Comment by felangel** [comment]
I’m in favor of removing the build apk but I think we should maintain consistency and avoid introducing multiple commands/aliases  for the same functionality to limit the api surface and reduce confusion. The reason we added --artifact was because release is still uploading the aab the only difference is whether we also build an apk. To me, shorebird release apk makes it seem like we’re uploading the apk which could also be confusing

**Comment by felangel** [comment]
We also should align on the other build commands. We currently have:

- `shorebird build ipa`
- `shorebird build aar`
- `shorebird build apk`
- `shorebird build app_bundle`

**Comment by bryanoltman** [comment]
As discussed on Discord, we will move forward by hiding these commands
