### ISSUE TITLE
`shorebird releases delete` for a specific platform

### ISSUE THREAD

**Issue by eseidel** [shorebirdtech/shorebird#909]
Right now if you want to delete a release we delete both the iOS and Android release for a version, you have no choice.

**Comment by felangel** [comment]
We should likely avoid doing this work in the CLI and instead focus on porting the existing delete functionality to the console and then supporting this from the console.

**Comment by eseidel** [comment]
Requires backend changes, most likely going to end up as a console function?

**Comment by felangel** [comment]
This is done and is now available through the console.

**Comment by lukemmtt** [comment]
@felangel @eseidel 
I was working out an agentic release workflow, and I came upon this limitation, realizing that neither the CLI nor API, nor the Web Console, seem to allow per-platform deletion operation. Yet I see @felangel mentioned that, at least at one point in the past, this was supported in the console; I can't see such a thing. Is it safe to say that it's gone for good?

P.S., to be clear, this is a very low priority, just trying to close the loop. I erroneously had an agent delete my shorebird release for all platforms instead of just one, and now I'm SOL w/r/t patching my release. Thankfully the thing I was trying to patch was trivial to begin, so it doesn't matter much, but yeah 😂

**Comment by eseidel** [comment]
I think we're going to expose all this in api soon.  I have a PR up, but we haven't landed it yet.  Filed https://github.com/shorebirdtech/shorebird/issues/3665 to track.

**Comment by lukemmtt** [comment]
Wonderful, thanks Eric 🙏🏻
